### ISSUE TITLE
[Evaluator] GitHub repository metadata extraction fails

### ISSUE THREAD

**Issue by abnerbog** [inab/openEBench-nuxt#656]
**Bug description:**

The FAIR evaluator tool fails to extract metadata from my GitHub repository. 

**To reproduce:**

1. Install [OEB FAIRsoft Evaluator](https://github.com/apps/oeb-fairsoft-evaluator/) 
    - Grant the required read/write permissions for all repositories.
2. Go to the [FAIRsoft evaluator app](https://openebench.bsc.es/observatory/Evaluation/)
3. In Step 1, select 'GitHub repository' as the metadata source 
4. Enter the URL: 'https://github.com/inab/FAIRsoft_indicators' (or a fork, e.g., 'https://github.com/abnerbog/FAIRsoft_indicators')
    - This was repeated with multiple GitHub repositories in my workspace and resulted in the same error.

**Error message:**

![image-1](https://github.com/user-attachments/assets/83565be0-3e74-4cde-b297-8253bd5eae99)

**Environment:**  

Device: Dell laptop (x64)   
OS: Windows 11 Pro  
Browser: Google Chrome

**Comment by EvaMart** [comment]
Hello,

Thank you for reporting this issue.

I have restarted the API responsible for the problem, and it appears to be working correctly now. Could you please check on your end and let us know if you encounter any further issues?

Thank you!

**Comment by abnerbog** [comment]
Thanks for the reply ! The metadata extraction (and subsequent steps) using the GitHub URL works correctly now.

Will make a new issue if we encounter any other problems. Thanks again for building this tool !

**Comment by abnerbog** [comment]
Hello,

I'd like to reopen this issue as I am now encountering the same bug with the [FAIRsoft Evaluator tool](https://openebench.bsc.es/observatory/Evaluation/). The tool fails when attempting to extract metadata using a GitHub URL as input (e.g., 'https://github.com/inab/FAIRsoft_indicators' or 'https://github.com/abnerbog/FAIRsoft_indicators'). The environment I am using remains the same as described in the initial issue.

Thank you again for your assistance here!

**Comment by EvaMart** [comment]
Hello, 

Thank you for bringing this issue to our attention. The API handling GitHub authentication had crashed due to a function that was not handling errors as it should have. The API is now back up and running, and I will be improving the error handling to prevent similar issues from occurring in the future.  I apologize for any inconvenience this may have caused.

Additionally, I want to inform you about an update happening this weekend. Based on user feedback, we understand that some users prefer not to grant apps write permissions. To accommodate this, we are splitting the functionality into two separate GitHub Apps—[one](https://github.com/apps/metadata-extractor-for-fairsoft) with read-only permissions and [one](https://github.com/apps/metadata-updater-for-fairsoft) with write permissions. This way, you can choose the option that best fits your needs. 

We are also adding logging to the indicator results to provide better insights into where the results originate from, and the possibility to export a citation .cff file directly from the interface. 

Thanks!

Eva

**Comment by abnerbog** [comment]
Eva, thank you for your prompt and detailed response, and for restarting the API! The update to split read-only and write permissions in the evaluator tool is also very helpful to know. I’m currently reviewing the endpoints in the [metadata extractor](https://github.com/apps/metadata-extractor-for-fairsoft) and believe this will be quite valuable moving forward. I may have additional questions about integrating these apps into the evaluator tool, which I would raise in a separate issue. 

Thanks again for your continued work on this excellent tool!

Abner

**Comment by abnerbog** [comment]
Hi Eva!

I am reopening this issue as the tool is currently hanging on the metadata extraction step using a GitHub URL as input.

**Comment by EvaMart** [comment]
The server is up and running, so I close this issue.

**Comment by abnerbog** [comment]
Apologies for all the comments on this issue thread ! For some reason the tool is not running and I am seeing the below error message again when attempting to extract metadata from the repository https://github.com/inab/oeb-visualizations : 

![image](https://github.com/user-attachments/assets/1bb5485b-6a5e-454d-b52f-51c12f812a31)

**Comment by EvaMart** [comment]
The server was down earlier 😣, but it’s back up and running now. Thanks for your patience! If the problem recurs, feel free to open a new issue.
