### ISSUE TITLE
[Evaluator] Unable to make pull request to add metadata/citation files

### ISSUE THREAD

**Issue by abnerbog** [inab/openEBench-nuxt#664]
**Bug description:**

The FAIR evaluator tool fails to extract metadata from my GitHub repository.

**To reproduce:**

1. Install [Metadata Updater for FAIRsoft](https://github.com/apps/metadata-updater-for-fairsoft/) 
    - Grant the required read/write permissions for all repositories.
2. Go to the [FAIRsoft evaluator app](https://openebench.bsc.es/observatory/Evaluation/)
3. In Step 1, select 'GitHub repository' as the metadata source 
4. Enter the URL: 'https://github.com/abnerbog/hydroshare' and proceed without making edits to metadata
5. In step 4, make a pull request of the metadata file (JSON-LD format) to GitHub repository
    - This also occurs when making a PR of the citation file (CFF format)
    - Note that I do not see this error when using the default repository 'https://github.com/inab/oeb-visualizations' 

**Error message:**

![image](https://github.com/user-attachments/assets/eda0dc52-e0b8-4deb-9794-703cc06a2dd4)

**Environment:**

Device: Dell laptop (x64)
OS: Windows 11 Pro
Browser: Google Chrome

**Comment by EvaMart** [comment]
Hi Abner,

The issue occurred because the API ([github-metadata-api](https://github.com/inab/github-metadata-api)) couldn’t identify a target branch for the PR, which led to the error. I’ve updated both the API and the front end to ensure the branch name is provided, so this issue should no longer happen.

Thank you for bringing this to our attention!

**Comment by abnerbog** [comment]
Thanks so much again Eva!
